#!/bin/sh

curl "http://fabien.benetou.fr/Site/AllRecentChanges?action=source" | head -20 | sed "s/^\* \[\[\(.*\)\]\]  .*/\1/" | sed "s/\./\//" | sed s"/.*/\"fabien.benetou.fr\/\0\",/" >> render_multi_url.js 
